### ISSUE TITLE
doesn't work for python2?

### ISSUE THREAD

**Issue by krupan** [bluepeppers/pip2arch#18]
```
$ pip2arch.py -p python2 python-dulwich
Traceback (most recent call last):
  File "/usr/bin/pip2arch.py", line 251, in <module>
    main()
  File "/usr/bin/pip2arch.py", line 235, in main
    version=args.version, outname=args.outname)
  File "/usr/bin/pip2arch.py", line 65, in get_package
    logging.info('Using version %s' % versions[0])
IndexError: list index out of range
```

**Comment by fossdd** [comment]
That's another issue. You try to package [`python-dulwich`](https://pypi.org/project/python-dulwich/) which does not exist. I guess you mean [`dulwich`](https://pypi.org/project/dulwich/).

This is a example how it works:

```bash
$ pip2arch.py -p python2 dulwich
Got package information
PKGBUILD written
```

The error message will be improved in https://github.com/lclarkmichalek/pip2arch/pull/21
